[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# RPC endpoints - Using 1inch Web3 RPC
[rpc_endpoints]
mainnet = "https://api.1inch.dev/web3/1"
polygon = "https://api.1inch.dev/web3/137"
polygonAmoy = "https://rpc-amoy.polygon.technology"
base = "https://api.1inch.dev/web3/8453"
baseSepolia = "https://sepolia.base.org"

# Etherscan API keys for verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
polygonAmoy = { key = "${POLYGONSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
baseSepolia = { key = "${BASESCAN_API_KEY}" }

# Gas reporting
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }